### ISSUE TITLE
how can we initial widget index ?

### ISSUE THREAD

**Issue by jemariads** [UdaraWanasinghe/FlutterCarouselSlider#1]
Hi @UdaraWanasinghe 

first thank you for great widget,

I wanna ask you, how can we set the initial index for this widget?

Thank you,
Erwan

**Comment by UdaraWanasinghe** [comment]
Thank you for asking. Currently there is no property to define initial index. I will add it in the next release.

**Comment by tlworkssoftware** [comment]
@UdaraWanasinghe Congratulations on the package, would you have a forecast or an option for a workaround?

**Comment by tlworkssoftware** [comment]
Would this feature have a release forecast?
