### ISSUE TITLE
[Feature]optional slideTransform and slideIndicator

### ISSUE THREAD

**Issue by shinriyo** [UdaraWanasinghe/FlutterCarouselSlider#2]
if `slideTransform` is null, use `slideTransform: DefaultTransform(),` is better.

and slideIndicator is not needed.
I put `indicatorRadius: 0,` instead.

```
            slideIndicator: CircularSlideIndicator(
              padding: EdgeInsets.only(bottom: 32),
              indicatorRadius: 0,
            ),
```

**Comment by shinriyo** [comment]
@UdaraWanasinghe Did you give up?

**Comment by shinriyo** [comment]
hey

**Comment by UdaraWanasinghe** [comment]
That looks nice. Thank you for the suggestion. ;)
