### ISSUE TITLE
[Feature]border for indicator

### ISSUE THREAD

**Issue by shinriyo** [UdaraWanasinghe/FlutterCarouselSlider#3]
Add border for indicator

**Comment by shinriyo** [comment]
Like this
![Like_this](https://user-images.githubusercontent.com/396927/94405352-63c7b580-01ab-11eb-8aff-86c038fb0b00.png)

**Comment by shinriyo** [comment]
@UdaraWanasinghe Are you still maintainance?

**Comment by UdaraWanasinghe** [comment]
Custom indicators can be created by implementing `SlideIndicator` class. Please see [carousel_slider_indicators.dart](https://github.com/UdaraWanasinghe/FlutterCarouselSlider/blob/master/lib/carousel_slider_indicators.dart) for more details.
