### ISSUE TITLE
[Feature Request] Option to trigger callback on slide

### ISSUE THREAD

**Issue by alekes** [UdaraWanasinghe/FlutterCarouselSlider#8]
First of all: Thanks for the nice package!

It would be great if we could define a callback which is triggered on slide left or right.

**Comment by UdaraWanasinghe** [comment]
Feature added [f154d5e896febf5402dc4a2edd0c7c4e57ba7788](https://github.com/UdaraWanasinghe/FlutterCarouselSlider/pull/12/commits/f154d5e896febf5402dc4a2edd0c7c4e57ba7788)
